apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-public
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  labels:
    app: pingfederate
    tier: engine
  name: pingfederate
  namespace: anydevops
spec:
  rules:
  - host: ${K8S_ENVIRONMENT}pingfederate.anydevops.com
    http:
      paths:
      - backend:
          serviceName: pingfederate
          servicePort: 443
        path: /
  tls:
  - hosts:
    - ${K8S_ENVIRONMENT}pingfederate.anydevops.com
    secretName: anydevops-tls-secret